apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ija+GXNp3V+MaxmpFCMaSgoRiPjBhj7D,iv:5kXmUdjL5ARW6uFxJHc1wztW4c7iRQ5RmlWu8pUU2Zw=,tag:ksYA12UwEgnSZ9DZWGyCng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1huwtfh57f93ceeav3k9xdmmnj90yzdaa05szskg2hat2rrq00yesyl2y5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZE1vZC83TDFIZXM1eTBq
            R3R2QnhFODM2SDJvNVJ2VVozNTAreTFWdUg0CjNQUnl1akRyYy9FSTlWVkZmMS9M
            NlZDNWEwRXBYRXdiRndDWStxN3pqNkUKLS0tIGdGWmdKeW5vL3J1RXFSaFU3Y3BI
            RXp3VHV5b0doL2dTVmJSY1FXNWJFUXMKPPHxOLCwiw2ZcaqYwsoeOZ51XkIEf1BP
            h0NhBSy+W+rO6VnN0nArzQGmQXkB80lQasenD+e18UvFP//9VlTmXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T20:37:56Z"
    mac: ENC[AES256_GCM,data:gR/48PEbcRjVxvZUTpntnzH9H/s1WYHHK3NtvipUCsKDHyajdYvzq1sFVqRV6iPl2rTbiCTd4Q0l3oIIiUVwF6ZUoE4UX9Q0UZPwBgb1wK4kOeIv7MRU1dhKPw6BpYPcBdzgor0f9sjhyFXlsa79Xu01L3Vi5TlDw+5ohiA8/zs=,iv:CSIwD9v3ZffjD4m4zQM6HDE8qDnK0urGDofSiIZjSUc=,tag:7SBkbvi/AlK7qUJN2mxjrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
